import Article from "@/types/article";

export const articleData: Array<Article.ArticleBaseInterface> = [
  // {
  //   id: "",
  //   author: "Kwanwoo",
  //   category: "ML",
  //   filePath: "",
  //   imageUrl: "",
  //   articleId: "",
  //   title: "",
  //   subtitle: "",
  //   createdAt: new Date(2022, 3, 16),
  //   updatedAt: new Date(2022, 3, 16),
  //   views: 0,
  //   recommend: false,
  // },
  {
    id: "physics-based-human-motion-estimation",
    author: "Kwanwoo",
    category: "Research",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FW2kr3EPzHoesrZdC7EaD%2Fthumbnail%2Fphysics-based-human-motion-estimation-and-synthesis-from-videos-page-1-medium.jpg?alt=media&token=55f5ed10-29fb-4b2a-a709-fdb82f5aa7d8",
    articleId: "3f68d732af1d4296bfd1046cc272d343",
    title: "Physics-based Human Motion Estimation and Synthesis from Videos",
    subtitle:
      "Paper Review of Physics-based Human Motion Estimation and Synthesis from Videos.",
    createdAt: new Date(2021, 12, 19),
    updatedAt: new Date(2021, 12, 19),
    recommend: false,
    views: 0,
  },
  {
    id: "image-style-transfer",
    author: "Kwanwoo",
    category: "Research",
    filePath: "Articles/ml-adam/thumnail/optimizers7.gif",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FseNG50DNdOqoURLlxEd6%2Fthumbnail%2Fthe_scream.jpg?alt=media&token=5999f697-b8d5-4292-814d-6d0ba738fde0",
    articleId: "6653a3dcedac4b448ea64e3eae3d28d1",
    title: "Image Style Transfer (CNN)",
    subtitle:
      "Paper Review of Image Style Transfer Using Convolutional Neural Networks.",
    createdAt: new Date(2021, 12, 29),
    updatedAt: new Date(2021, 12, 29),
    views: 0,
    recommend: true,
  },
  {
    id: "ml-adam",
    author: "Kwanwoo",
    category: "ML",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FvFMrMMxKhYKCNsdIlfcz%2Fthumbnail%2Foptimizers7.gif?alt=media&token=419a41fc-e483-4f82-947a-c1e28b669cc0",
    articleId: "13bf689bcb15470782dab26a722ff88f",
    title: "Adaptive Moment Estimation (ADAM)",
    subtitle:
      "ADAM is the use of Gradient Descent with Momentum and RMSProp at the same time.",
    createdAt: new Date(2021, 9, 9),
    updatedAt: new Date(2021, 9, 9),
    views: 0,
    recommend: true,
  },
  {
    id: "basic-ml-ops-2",
    author: "Kwanwoo",
    category: "ML",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FrDYoMdCLpw7jIkQyVK20%2Fthumbnail%2F6066c22135b89828fead7950_visualize-seamlessly-weights-biases.jpg?alt=media&token=f6fd9df9-168b-4155-9c37-5fcfc216e3d5",
    articleId: "5addb5b2f38140f88d7c6e9056b0a26d",
    title: "02. MLOps: Model Monitoring - Weights and Bias",
    subtitle: "Basics of MLOps using basic vision project.",
    createdAt: new Date(2021, 12, 23),
    updatedAt: new Date(2021, 12, 23),
    views: 0,
    recommend: false,
  },
  {
    id: "vue-seo-friendly",
    author: "Kwanwoo",
    category: "Develop",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FhRhfHJwdNhRrzN9jCbW0%2Fthumbnail%2FVue_SEO.png?alt=media&token=9715f55d-589b-4faa-8f62-5af65e288421",
    articleId: "02ce25bf2e094b2b993f662d140c938e",
    title: "Creating SEO-friendly SPA with Vue.js + Firebase",
    subtitle: "Creating SEO-friendly SPA with Vue.js + Firebase.",
    createdAt: new Date(2022, 3, 11),
    updatedAt: new Date(2022, 3, 11),
    views: 0,
    recommend: false,
  },
  {
    id: "basic-ml-ops-1",
    author: "Kwanwoo",
    category: "ML",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FcRvN4bhHtSsr7ZhNVv4b%2Fthumbnail%2Fimg.png?alt=media&token=6d6abda7-0a5a-4955-890f-d1d393def57b",
    articleId: "cc0a09e33dda4d5f929d885dcd178613",
    title: "01. MLOps: Project Settings",
    subtitle: "Basics of MLOps using basic vision project.",
    createdAt: new Date(2021, 12, 16),
    updatedAt: new Date(2021, 12, 16),
    views: 0,
    recommend: false,
  },
  {
    id: "direct-delta-mesh",
    author: "Kwanwoo",
    category: "Research",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FbuIHJlD79tYvnKyrq2ns%2Fthumbnail%2Fteaser.jpg?alt=media&token=9728ed15-5493-4ece-a365-ac320686e1aa",
    articleId: "c82dbdc9f9234a2b85388a082c699890",
    title: "Direct Delta Mesh Skinning Compression with Continuous Examples",
    subtitle:
      "Direct Delta Mesh (DDM) is a high-quality, direct skinning method with a low setup cost.",
    createdAt: new Date(2022, 1, 4),
    updatedAt: new Date(2022, 1, 4),
    views: 0,
    recommend: false,
  },
  {
    id: "physics-based-human-motion-estimation",
    author: "Kwanwoo",
    category: "ML",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FW2kr3EPzHoesrZdC7EaD%2Fthumbnail%2Fphysics-based-human-motion-estimation-and-synthesis-from-videos-page-1-medium.jpg?alt=media&token=55f5ed10-29fb-4b2a-a709-fdb82f5aa7d8",
    articleId: "3f68d732af1d4296bfd1046cc272d343",
    title: "Physics-based Human Motion Estimation and Synthesis from Videos",
    subtitle:
      "Paper review of Physics-based Human Motion Estimation and Synthesis from Videos",
    createdAt: new Date(2021, 12, 19),
    updatedAt: new Date(2021, 12, 19),
    views: 0,
    recommend: false,
  },
  {
    id: "bayesian-probability",
    author: "Kwanwoo",
    category: "Mathematics",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FRb2haDX6ts4pVvtwzGnP%2Fthumbnail%2Fformula-bayes-theorem.png?alt=media&token=90c93026-184a-48d8-8af3-043f849e3ae4",
    articleId: "e7af26db4fd74984940c375ed57a6ee9",
    title: "Bayesian probability",
    subtitle:
      "Bayesian probability is an interpretation of the concept of probability.",
    createdAt: new Date(2021, 8, 26),
    updatedAt: new Date(2021, 8, 26),
    views: 0,
    recommend: false,
  },
  {
    id: "vanilla-gan",
    author: "Kwanwoo",
    category: "Research",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FFrwarCElLxB1Pz3pRKMI%2Fthumbnail%2Fgan_architecture-1.png?alt=media&token=20d9dcd4-c3e0-4180-9b25-74c992fe03ab",
    articleId: "9c86fb47125247b5aff19e66022173fa",
    title: "Vanilla Generative Adversarial Networks(GAN) Review",
    subtitle: "Framework for estimating generative models.",
    createdAt: new Date(2021, 8, 24),
    updatedAt: new Date(2021, 8, 24),
    views: 0,
    recommend: false,
  },
  {
    id: "kl-divergence",
    author: "Kwanwoo",
    category: "Mathematics",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FDCdikRVyrxb3RcAjyAw3%2Fthumbnail%2Fmarketing%20expectations%20vs%20reality.png?alt=media&token=09be0683-6fe0-486a-ac91-1de2419bc79d",
    articleId: "d363a3f840774c7cb2c27b9548e4db6d",
    title: "KL Divergence",
    subtitle:
      "KL Divergence(Kullback-Leibler) also know as  Relative Entropy is all about difference between two distribution.",
    createdAt: new Date(2021, 8, 27),
    updatedAt: new Date(2021, 8, 27),
    views: 0,
    recommend: false,
  },
  {
    id: "linear-regression",
    author: "Kwanwoo",
    category: "ML",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FD1ybQOcmtjGIXDJ9y5ok%2Fthumbnail%2FNormdist_regression.png?alt=media&token=deed08e5-bf86-4d8d-88bd-2f7ff08fbdd2",
    articleId: "a11e62c3eb714cc7a054b4114a170869",
    title: "Linear Regression",
    subtitle:
      "linear regression is a linear approach for modelling the relationship between a scalar response and one or more explanatory variables.",
    createdAt: new Date(2021, 9, 9),
    updatedAt: new Date(2021, 9, 9),
    views: 0,
    recommend: false,
  },
  {
    id: "gradient-descent",
    author: "Kwanwoo",
    category: "ML",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FBjlmJreWBg4l1WWMzU4y%2Fthumbnail%2F99A123355A3A2DAF12.png?alt=media&token=744cba79-7441-42de-9415-5cccad4c5949",
    articleId: "172a04ea21d142c09fbb5bedd7e18bcb",
    title: "Gradient Descent",
    subtitle:
      "Gradient descent method is also called as steepest descent method.",
    createdAt: new Date(2021, 9, 16),
    updatedAt: new Date(2021, 9, 16),
    views: 0,
    recommend: false,
  },
  {
    id: "glide",
    author: "Kwanwoo",
    category: "Research",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2FOeJ0vRGHBMk11mP7Wgae%2Fthumbnail%2Fimage-95.png?alt=media&token=61166319-3f9b-4c3b-9f43-53457ca003cd",
    articleId: "958ef8a661ea46d0bfbfcb5654c78fd9",
    title: "GLIDE",
    subtitle:
      "Towards Photorealistic Image Generation and Editing with Text-Guided Diffusion Models.",
    createdAt: new Date(2022, 1, 4),
    updatedAt: new Date(2022, 1, 4),
    views: 0,
    recommend: false,
  },
  {
    id: "generate-mathmatics",
    author: "Kwanwoo",
    category: "Research",
    filePath: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/woozlabs.appspot.com/o/Post%2F8JmrSOEN1kGyHyJpYALO%2Fthumbnail%2FFIJH4RrXoAYy1X-.jpg?alt=media&token=f865af82-a493-4f55-8b90-814f5ed319df",
    articleId: "e780077a9e0a4328b53bfa7cb999ca53",
    title: "Generate Mathematics Problems by Program Synthesis",
    subtitle:
      "A Neural Network Solves and Generates Mathematics Problems by Program Synthesis: Calculus, Differential Equations, Linear Algebra, and More.",
    createdAt: new Date(2022, 1, 4),
    updatedAt: new Date(2022, 1, 4),
    views: 0,
    recommend: false,
  },
];

export default { articleData };
